[package]
name = "openltomanager"
version = "0.1.0"
authors = ["nathros"]
edition = "2024"
rust = "1.95"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Keep the same versions as https://github.com/DioxusLabs/dioxus/blob/main/Cargo.toml
axum = { version = "0.8.4", optional = true }
balloon-hash = { version = "0.4.0", optional = true }
base64 = { version = "0.22.1", optional = true }
chrono = { version = "0.4.39", features = ["serde"] }
dioxus = { version = "0.7.9", features = ["router", "fullstack"] }
enum-iterator = { version = "2.3.0" } # Replace with std::mem::variant_count when stable
fontdb = { version = "0.23.0", optional = true }
krilla = { version = "0.7.0", optional = true }
krilla-svg = { version = "0.7.0", optional = true }
rand_core = { version = "0.6", features = ["std"], optional = true  }
reqwest = { version = "0.12.28", default-features = false, optional = true }
rusqlite = { version = "0.40.1", features = ["bundled", "chrono"], optional = true }
serde = { version = "1.0.228", features = [] }
serde_json = { version = "1.0.140", features = [], optional = true }
sha2 = { version = "0.10.9", optional = true }
tokio = { version = "1.48", features = ["process"], optional = true }
tracing = { version = "0.1.41" }
tracing-subscriber = { version = "0.3.20", optional = true }
usvg  = { version = "0.45.1", optional = true }
uuid  = { version = "1.17.0", features = ["v4"], optional = true }
uzers = { version = "0.12.2", optional = true }
whoami = { version = "2.1.2", optional = true }

[dev-dependencies]
tempdir = "0.3.7"

[features]
default = ["web", "server"]
web = ["dioxus/web",
       "disable_tracing", # Remove logging for release wasm to reduce size
       "auto_login",      # Testing only for debug builds
]
# desktop = ["dioxus/desktop"]
# mobile = ["dioxus/mobile"]
server = ["dioxus/server",
          "dep:axum",
          "dep:balloon-hash",
          "dep:base64",
          "dep:krilla",              # PDF
          "dep:krilla-svg",          # PDF
          "dep:fontdb",              # PDF
          "dep:rand_core",
          "dep:reqwest",
          "dep:rusqlite",
          "dep:serde_json",          # /dev only
          "dep:sha2",
          "dep:tokio",
          "dep:tracing-subscriber",
          "dep:usvg",                # PDF
          "dep:uuid",
          "dep:uzers",
#         "slow_server",             # Testing only
          "auto_login",              # Testing only
          "dep:whoami"]
disable_tracing = ["tracing/release_max_level_off"]
slow_server = [] # Testing only, adds delay to all backend requests
auto_login = []  # Testing only, auto login as admin for debug build only

[lints.clippy]
unwrap_used = "deny"
allow-unwrap-in-tests = "allow"

# https://dioxuslabs.com/learn/0.5/cookbook/optimizing/#build-configuration
[profile.release]
opt-level = "z"
debug = false
lto = true
codegen-units = 1
panic = "abort"
strip = true
incremental = false

# https://book.leptos.dev/deployment/binary_size.html
[profile.wasm-release]
inherits = "release"
opt-level = "z"
lto = true
codegen-units = 1
