[package]
name = "openltomanager"
version = "0.1.0"
authors = ["nathros"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.43", features = ["serde"] }
dioxus = { version = "0.7.5", features = ["router", "fullstack"] }
reqwest = { version = "0.12.28", features = [], optional = true }
rusqlite = { version = "0.38.0", features = ["bundled", "chrono"], optional = true }
serde = { version = "1.0.228", features = [] }
serde_json = { version = "1.0.149", features = [], optional = true } # /dev only
tokio = { version = "1.49.0", features = ["process"], optional = true }
tracing = { version = "0.1.44" }
tracing-subscriber = { version = "0.3.22", optional = true }
uzers = { version = "0.12.2", optional = true }
whoami = { version = "2.1.1", optional = true }

[dev-dependencies]
tempdir = "0.3.7"

[features]
default = ["web", "server"]
web = ["dioxus/web"]
# desktop = ["dioxus/desktop"]
# mobile = ["dioxus/mobile"]
server = ["dioxus/server",
          "dep:reqwest",
          "dep:rusqlite",
          "dep:serde_json", # /dev only
          "dep:tokio",
          "dep:tracing-subscriber",
          "dep:uzers",
#         "slow_server" # Testing only
          "dep:whoami"]
slow_server = [] # Testing only, adds delay to all backend requests

[lints.clippy]
unwrap_used = "deny"
allow-unwrap-in-tests = "allow"

# https://dioxuslabs.com/learn/0.5/cookbook/optimizing/#build-configuration
[profile.release]
opt-level = "z"
debug = false
lto = true
codegen-units = 1
panic = "abort"
strip = true
incremental = false

# https://book.leptos.dev/deployment/binary_size.html
[profile.wasm-release]
inherits = "release"
opt-level = "z"
lto = true
codegen-units = 1
