#:schema https://raw.githubusercontent.com/DioxusLabs/dioxus/main/packages/cli/schema.json

[application]

[web]
pre_compress = true

[web.app]

# HTML title tag content
title = "openltomanager"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
