/* == Generated by: generate-css-const.sh == */

#[non_exhaustive]
pub struct Css; // CSS class names

impl Css {
    pub const COLOUR_SCHEME: &str = "colour-scheme"; // Defined in assets/css/:root.css line 48
    pub const COLOUR_SCHEME_LIGHT: &str = "colour-scheme-light"; // Defined in assets/css/:root.css line 49
    pub const COLOUR_SCHEME_DARK: &str = "colour-scheme-dark"; // Defined in assets/css/:root.css line 50
    pub const MAIN_HEADER: &str = "main-header "; // Defined in assets/css/header.css line 1
    pub const MAIN_HEADER_LOGO: &str = "header-logo "; // Defined in assets/css/header.css line 30
    pub const MAIN_ASIDE: &str = "main-aside "; // Defined in assets/css/header.css line 42
    pub const HEADER_USER: &str = "header-user "; // Defined in assets/css/header.css line 56
    pub const HEADER_DROPDOWN: &str = "header-dropdown "; // Defined in assets/css/header.css line 66
    pub const HEADER_DROPDOWN_CONTENT: &str = "header-dropdown-content "; // Defined in assets/css/header.css line 73
    pub const HEADER_DROPDOWN_NESTED: &str = "nested "; // Defined in assets/css/header.css line 87
    pub const FLOAT_RIGHT: &str = "float-right "; // Defined in assets/css/header.css line 92
    pub const HEADER_COL: &str = "header-colour "; // Defined in assets/css/header.css line 95
    pub const RAINBOW: &str = "rainbow "; // Defined in assets/css/header.css line 98
    pub const ID_ACCENT_PICKER: &str = "accent-picker"; // Defined in assets/css/header.css line 101
    pub const HEADER_ANCHOR_BASE: &str = "h-base"; // Defined in assets/css/header.css line 120
    pub const HEADER_ANCHOR_POSITION: &str = "header-anchor-position "; // Defined in assets/css/header.css line 124
    pub const ACCORDION_CONTAINER: &str = "accordion-container "; // Defined in assets/css/accordion.css line 1
    pub const ACTIVE: &str = "active "; // Defined in assets/css/accordion.css line 23
    pub const ICON_LIST_ITEM: &str = "icon-list-item "; // Defined in assets/css/icon-list.css line 1
    pub const ICON: &str = "icon "; // Defined in assets/css/icon.css line 1
    pub const SM: &str = "sm "; // Defined in assets/css/icon.css line 7
    pub const MD: &str = "md "; // Defined in assets/css/icon.css line 11
    pub const LG: &str = "md "; // Defined in assets/css/icon.css line 15
    pub const FORM_GRID: &str = "form-grid "; // Defined in assets/css/forms.css line 1
    pub const INPUT: &str = "input "; // Defined in assets/css/forms.css line 12
    pub const SELECT: &str = "select "; // Defined in assets/css/forms.css line 13
    pub const INPUT_CONTAINER: &str = "input-container "; // Defined in assets/css/forms.css line 49
    pub const INPUT_ERROR_ICON: &str = "input-error-icon "; // Defined in assets/css/forms.css line 65
    pub const RADIO_PILL_CONTAINER: &str = "radio-pill-container "; // Defined in assets/css/forms.css line 91
    pub const INPUT_MESSAGE: &str = "input-message "; // Defined in assets/css/input.css line 1
    pub const MESSAGE: &str = "message "; // Defined in assets/css/message.css line 1
    pub const CARD: &str = "card "; // Defined in assets/css/card.css line 1
    pub const V_DIVIDER: &str = "v-divider "; // Defined in assets/css/card.css line 7
    pub const CARD_OVERVIEW: &str = "card-overview "; // Defined in assets/css/card.css line 13
    pub const CARD_OVERVIEW_STATUS: &str = "card-overview-status "; // Defined in assets/css/card.css line 32
    pub const CODE_BLOCK: &str = "code-block "; // Defined in assets/css/code-block.css line 1
    pub const BTN: &str = "btn "; // Defined in assets/css/button.css line 1
    pub const BTN_PRI: &str = "pri "; // Defined in assets/css/button.css line 27
    pub const PDF_PREVIEW: &str = "pdf-preview "; // Defined in assets/css/library.css line 1
    pub const LOGIN_CONTAINER: &str = "login-container "; // Defined in assets/css/login.css line 1
    pub const MENU_CONTAINER: &str = "menu-container "; // Defined in assets/css/menu.css line 1
    pub const MENU_GROUP: &str = "menu-group "; // Defined in assets/css/menu.css line 9
    pub const ICON_TAPE: &str = "tape "; // Defined in assets/css/menu.css line 21
    pub const DEBUG_FLOAT: &str = "debug-float "; // Defined in assets/css/debug.css line 1
    pub const DEBUG_MENU: &str = "debug-menu "; // Defined in assets/css/debug.css line 5
    pub const REVERT: &str = "revert "; // Defined in assets/css/common.css line 38
    pub const LINK: &str = "link "; // Defined in assets/css/common.css line 49
    pub const MONOSPACE: &str = "monospace "; // Defined in assets/css/common.css line 52
    pub const FLEX_ROW: &str = "flex-row "; // Defined in assets/css/common.css line 56
    pub const FLEX_COL: &str = "flex-col "; // Defined in assets/css/common.css line 59
    pub const FLEX_CENTRE: &str = "flex-centre "; // Defined in assets/css/common.css line 67
    pub const FLEX_ALIGN_LEFT: &str = "align-left "; // Defined in assets/css/common.css line 72
    pub const FLEX_ALIGN_CENTRE: &str = "align-centre "; // Defined in assets/css/common.css line 75
    pub const NO_GAP: &str = "no-gap "; // Defined in assets/css/common.css line 78
    pub const GAP_S: &str = "gap-s "; // Defined in assets/css/common.css line 81
    pub const SELECTED: &str = "selected "; // Defined in assets/css/common.css line 85
    pub const BG: &str = "bg "; // Defined in assets/css/common.css line 98
    pub const COL: &str = "col "; // Defined in assets/css/common.css line 113
    pub const HOVER: &str = "hover "; // Defined in assets/css/common.css line 128
    pub const ID_SNA: &str = "sna"; // Defined in assets/css/common.css line 132
    pub const ID_SAND: &str = "sandpit"; // Defined in assets/css/common.css line 154
}
