/* == Generated by: generate-css-const.sh == */

#[non_exhaustive]
pub struct Css; // CSS class names

impl Css {
    pub const COLOUR_SCHEME: &str = "colour-scheme"; // Defined in assets/css/:root.css line 46
    pub const COLOUR_SCHEME_LIGHT: &str = "colour-scheme-light"; // Defined in assets/css/:root.css line 47
    pub const COLOUR_SCHEME_DARK: &str = "colour-scheme-dark"; // Defined in assets/css/:root.css line 48
    pub const MAIN_HEADER: &str = "main-header "; // Defined in assets/css/header.css line 1
    pub const MAIN_HEADER_LOGO: &str = "header-logo "; // Defined in assets/css/header.css line 19
    pub const MAIN_ASIDE: &str = "main-aside "; // Defined in assets/css/header.css line 31
    pub const HEADER_USER: &str = "header-user "; // Defined in assets/css/header.css line 45
    pub const HEADER_DROPDOWN: &str = "header-dropdown "; // Defined in assets/css/header.css line 55
    pub const HEADER_DROPDOWN_CONTENT: &str = "header-dropdown-content "; // Defined in assets/css/header.css line 62
    pub const HEADER_DROPDOWN_NESTED: &str = "nested "; // Defined in assets/css/header.css line 76
    pub const FLOAT_RIGHT: &str = "float-right "; // Defined in assets/css/header.css line 85
    pub const HEADER_COL: &str = "header-colour "; // Defined in assets/css/header.css line 88
    pub const RAINBOW: &str = "rainbow "; // Defined in assets/css/header.css line 91
    pub const ID_ACCENT_PICKER: &str = "accent-picker"; // Defined in assets/css/header.css line 94
    pub const ICON_LIST_ITEM: &str = "icon-list-item "; // Defined in assets/css/icon-list.css line 1
    pub const ICON: &str = "icon "; // Defined in assets/css/icon.css line 1
    pub const MESSAGE: &str = "message "; // Defined in assets/css/message.css line 1
    pub const CARD: &str = "card "; // Defined in assets/css/card.css line 1
    pub const BTN: &str = "btn "; // Defined in assets/css/button.css line 1
    pub const BTN_PRI: &str = "pri "; // Defined in assets/css/button.css line 19
    pub const LOGIN_CONTAINER: &str = "login-container "; // Defined in assets/css/login.css line 1
    pub const MENU_CONTAINER: &str = "menu-container "; // Defined in assets/css/menu.css line 1
    pub const MENU_GROUP: &str = "menu-group "; // Defined in assets/css/menu.css line 9
    pub const ICON_TAPE: &str = "tape "; // Defined in assets/css/menu.css line 17
    pub const FLEX_ROW: &str = "flex-row "; // Defined in assets/css/common.css line 30
    pub const FLEX_COL: &str = "flex-col "; // Defined in assets/css/common.css line 33
    pub const FLEX_CENTRE: &str = "flex-centre "; // Defined in assets/css/common.css line 42
    pub const NO_GAP: &str = "no-gap "; // Defined in assets/css/common.css line 47
    pub const SHOW: &str = "show "; // Defined in assets/css/common.css line 50
    pub const SELECTED: &str = "selected "; // Defined in assets/css/common.css line 53
    pub const SM: &str = "sm "; // Defined in assets/css/common.css line 57
    pub const MD: &str = "md "; // Defined in assets/css/common.css line 61
    pub const SCREEN_FILL: &str = "screen-fill "; // Defined in assets/css/common.css line 65
    pub const BG: &str = "bg "; // Defined in assets/css/common.css line 78
    pub const ID_SNA: &str = "sna"; // Defined in assets/css/common.css line 93
}
