/* == Generated by: generate-svg-sprites.sh == */

#[non_exhaustive]
pub struct Icons;

impl Icons {
    pub const ERROR: &str = "error ";
    pub const INFO: &str = "info ";
    pub const SUCCESS: &str = "success ";
    pub const WARNING: &str = "warning ";
    pub const HOME: &str = "home ";
    pub const NOTIFICATION: &str = "notification ";
    pub const USER: &str = "user ";
    pub const SANDPIT: &str = "sandpit ";
    pub const LOGOUT: &str = "logout ";
    pub const PALETTE: &str = "palette ";
    pub const CONTRAST: &str = "contrast ";
    pub const CHEVRON_RIGHT: &str = "chevron-right ";
    pub const LIGHT: &str = "light ";
    pub const DARK: &str = "dark ";
    pub const SYSTEM: &str = "system ";
    pub const LIST: &str = "list ";
    pub const BUG: &str = "bug ";
    pub const BOOK: &str = "book ";
    pub const SEARCH: &str = "search ";
}
