/* == Generated by: generate-svg-sprites.sh == */

#[non_exhaustive]
pub struct Icons;

impl Icons {
    pub const ERROR: &str = "error ";
    pub const INFO: &str = "info ";
    pub const SUCCESS: &str = "success ";
    pub const WARNING: &str = "warning ";
    pub const HOME: &str = "home ";
    pub const NOTIFICATION: &str = "notification ";
    pub const USER: &str = "user ";
}
